support for pid+feedforward speed control complete
Eaglestrike/2023-RobotCode pull request #7
Opened 2022-12-14 09:30 UTC by SusanC3

2022-12-14 17:06 UTC, linc-mvla approved these changes

2022-12-15 02:33 UTC, gaborszita requested changes
Please see my comments - other than that it seems good to me. Good job cleaning up stuff though.

2022-12-15 02:33 UTC, gaborszita commented on src/main/cpp/Limelight.cpp
> +           // std::cout << "Something went wrong... more than 2 corners on bottom\n";
If this is commented out, why is there a need for the else?

2022-12-15 02:33 UTC, gaborszita commented on src/main/cpp/Limelight.cpp
> +      //  std::cout << "sus\n";
Same here: If this is commented out, why is there a need for an if?

2023-01-10 23:12 UTC, gaborszita approved these changes

2023-01-11 02:11 UTC, merged